/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#006e35',
        'on-primary-container': '#006970',
        'secondary-fixed': '#f2daff',
        'on-secondary-fixed': '#2e004e',
        'tertiary-fixed': '#62ff96',
        'inverse-on-surface': '#2c2f42',
        'on-error': '#690005',
        background: '#0e1223',
        'on-secondary': '#4c007d',
        'primary-container': '#00f0ff',
        'surface-container-low': '#171b2c',
        'on-tertiary': '#003918',
        'on-secondary-container': '#d7a4ff',
        'primary-fixed-dim': '#00dbe9',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#303446',
        'on-primary-fixed-variant': '#004f54',
        'secondary-container': '#6d11ad',
        'secondary-fixed-dim': '#e0b6ff',
        'inverse-surface': '#dee1fa',
        'surface-container-high': '#25293b',
        'on-tertiary-fixed': '#00210b',
        'surface-tint': '#00dbe9',
        'tertiary-container': '#34f885',
        'on-background': '#dee1fa',
        secondary: '#e0b6ff',
        'inverse-primary': '#006970',
        'on-secondary-fixed-variant': '#6a0baa',
        'primary-fixed': '#7df4ff',
        outline: '#849495',
        'tertiary-fixed-dim': '#00e475',
        surface: '#0e1223',
        'error-container': '#93000a',
        'surface-container': '#1b1f30',
        'outline-variant': '#3b494b',
        'surface-dim': '#0e1223',
        tertiary: '#dbffde',
        'surface-container-lowest': '#090d1e',
        'on-surface': '#dee1fa',
        'on-primary-fixed': '#002022',
        error: '#ffb4ab',
        'on-tertiary-fixed-variant': '#005226',
        'surface-bright': '#34384b',
        'surface-variant': '#303446',
        'on-primary': '#00363a',
        primary: '#dbfcff',
        'on-surface-variant': '#b9cacb',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'max-container': '1320px',
        'space-2xs': '0.25rem',
        'gutter-desktop': '1.5rem',
        'space-3xl': '4rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'gutter-mobile': '1rem',
        'space-xs': '0.5rem',
        'space-2xl': '3rem',
      },
      fontFamily: {
        'display-hero': ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'data-mono-num': ['Space Grotesk', 'sans-serif'],
        'label-telemetry-lg': ['Space Grotesk', 'sans-serif'],
        'label-telemetry-sm': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'data-mono-num': ['16px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-telemetry-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '700' }],
        'label-telemetry-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
